name: Profile metrics

on:
  schedule:
    - cron: "30 5 * * *"   # runs daily ~05:30 UTC; tweak as you like
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # LIGHT THEME
      - name: Metrics (light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: MedGit1000
          template: classic
          base: header, activity, repositories
          config_timezone: Africa/Casablanca
          config_twemoji: yes
          config_display: large
          # Enrich with more plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          output_action: commit
          committer_branch: main
          filename: assets/metrics-light.svg

      # DARK THEME
      - name: Metrics (dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: MedGit1000
          template: classic
          base: header, activity, repositories
          config_timezone: Africa/Casablanca
          config_twemoji: yes
          config_display: large
          config_theme: github_dark
          # Enrich with more plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          output_action: commit
          committer_branch: main
          filename: assets/metrics-dark.svg
